services:
  - type: web
    name: invoice-generator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    nodeVersion: 18.x
    healthCheckPath: /
    autoDeploy: true
    plan: free
    branch: main
    runtime: node
    envVars:
      - key: PYTHON_PATH
        value: python3
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free
    branch: main
    runtime: node
    nodeVersion: 18 